### ISSUE TITLE
Troubles connecting login/register form to the backend

### ISSUE THREAD

**Issue by MartaKirsch** [Mik-Grzeg/FamilyTree#11]
When I send a POST request to "http://localhost:8080/user/login" I can see those errors in the console:
![errors](https://user-images.githubusercontent.com/55833606/145998633-6c934480-86ef-4102-8487-fad5a8b7e652.png)
It seems that the request just hangs, because if you refresh the page you get this:
![after refresh](https://user-images.githubusercontent.com/55833606/145999725-228ef9d9-0d61-4fc0-b195-327f4b0fd04d.png)
When I pasted one of the requests Ada put in the Readme of Auth to the console, it also hangs:
![console](https://user-images.githubusercontent.com/55833606/145999911-ef732bd3-9bbb-4733-8a89-0e5bc5ebebcf.png)

Maybe I had to do something, set some env or else? I thought it would be quicker to ask than to look for it myself 😅

**Comment by Mik-Grzeg** [comment]
It was confusing so I fixed it with default that says 'changeme' https://github.com/Mik-Grzeg/FamilyTree/pull/12. Although, you can export env variable SECRET_KEY in `auth_api` and `auth_migrator` container by yourself
